### ISSUE TITLE
Bug: Win tile not detecting win condition for all levels with empty win tile at the start. Recreate: Level 2

### ISSUE THREAD

**Issue by Chick3nBoy** [seycara/Food-boy-saves-the-kitchen#29]
![image](https://user-images.githubusercontent.com/88542592/177989292-6843ddea-3758-4359-80f2-d9f7be3b8f6a.png)

**Comment by seycara** [comment]
Fixed bug: win tile continuously checks for a change from empty -> filled tile within win tile.
