### ISSUE TITLE
Bug: Object becomes cut when pushed into a knife only after the next turn. Recreate: Level 19: Push cheese into knife

### ISSUE THREAD

**Issue by Chick3nBoy** [seycara/Food-boy-saves-the-kitchen#32]
![image](https://user-images.githubusercontent.com/88542592/177999953-7d7731e8-eb1a-4dd4-a747-1bf67d46a917.png)

**Comment by seycara** [comment]
Has to do with hasMoved() function in Coordinator.cs not working as intended. This causes the function that updates sprites, SpriteUpdate(), not to update the sprites at all. Therefore, hasMoved cannot depend on this implementation of allMovementsComplete() and checkedMove.
