### ISSUE TITLE
Bug: Undo sometimes doesn't turn food back into player when leaving tile. Recreate: Level 10 Using apple, push apple out of you tile, undo, apple on left won't have movement

### ISSUE THREAD

**Issue by Chick3nBoy** [seycara/Food-boy-saves-the-kitchen#34]
![image](https://user-images.githubusercontent.com/88542592/178000875-650a35e6-de27-4bc0-a3b3-7bafa26a57a5.png)

**Comment by seycara** [comment]
Either:
1) Player tag is not being properly updated in the undo function
2) Players array is not correctly being updated in the undo function

**Comment by seycara** [comment]
Found the bug: During the undo, the tag on tiles are not checked and updated.
