### ISSUE TITLE
Bug: Win condition not detected for 2x1 and 2x2 win tile, Recreate: Level 7, push cheese into win tile, go to right side with tomato, put cheese above you tile, go to middle as tomato, go into win

### ISSUE THREAD

**Issue by Chick3nBoy** [seycara/Food-boy-saves-the-kitchen#42]
![image](https://user-images.githubusercontent.com/88542592/178091706-68a44e71-6318-4c69-a36b-679e12eaa195.png)

![image](https://user-images.githubusercontent.com/88542592/178091760-a310861e-b468-4254-b4da-f1bc7b58e80e.png)

**Comment by seycara** [comment]
update win condition function in winmanager is not updated properly.

**Comment by seycara** [comment]
Fixed problem where win condition checks grids on top instead of below the top left coordinate.
