### ISSUE TITLE
Bug: Win not detected when player moves into knife. Recreate: Level 19, push cheese into knife, push cheese left, move into knife

### ISSUE THREAD

**Issue by Chick3nBoy** [seycara/Food-boy-saves-the-kitchen#53]
![image](https://user-images.githubusercontent.com/88542592/178418593-8f4ed652-facb-42f1-bc3e-f57a9ece56d5.png)

**Comment by seycara** [comment]
Fixed bug in latest bug patch 12 July 2022.
