### ISSUE TITLE
Unintended mechanic: Food still gets cut if knife is heavy. let me know if hard to fix, can change the level

### ISSUE THREAD

**Issue by Chick3nBoy** [seycara/Food-boy-saves-the-kitchen#55]
![image](https://user-images.githubusercontent.com/88542592/178420134-7a4cb86e-e9a7-42e1-8b83-49e50fa5cce1.png)

**Comment by seycara** [comment]
Yes it is rather hard to fix and might take additional developer time. Seeing that the deadline is nearing for this project I think we can leave it as a feature instead.
