### ISSUE TITLE
Bug: Food can still move 1 tile after being cut. Recreate: walk into knife against a wall, move food else where

### ISSUE THREAD

**Issue by Chick3nBoy** [seycara/Food-boy-saves-the-kitchen#95]
![image](https://user-images.githubusercontent.com/88542592/180938780-1733a68b-d1bc-4604-b439-8f172b25c803.png)

**Comment by seycara** [comment]
Bug fixed.

`addAndRemovePlayers(new());` added to check for items that are not supposed to be moved anymore (not controlled by the user/player).
